USE `railway`;

DROP TABLE IF EXISTS `members`;
DROP TABLE IF EXISTS `settings`;
DROP TABLE IF EXISTS `branches`;

CREATE TABLE `branches` (
	`branch_code` VARCHAR(100) PRIMARY KEY,
    `branch_name` VARCHAR(255) NOT NULL,
    `profile_img` VARCHAR(255) DEFAULT 'default-avatar.png'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `branches` (`branch_code`, `branch_name`, `profile_img`)
VALUES ('comsci41', 'วิทยาการคอมพิวเตอร์ รุ่น 41', 'comsci41.png');

CREATE TABLE `members` (
    `id`            INT AUTO_INCREMENT PRIMARY KEY,
    `branch`        VARCHAR(100) NOT NULL DEFAULT 'comsci41',
    `name`          VARCHAR(255) NOT NULL,
    `amount`        DECIMAL(10,2) NOT NULL DEFAULT 100.00,
    `paid_months`   JSON NOT NULL,
    `paid_weeks`    JSON NOT NULL,
    `history`       JSON NOT NULL,
    `updated_at`    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`branch`) REFERENCES `branches`(`branch_code`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `settings` (
    `key`           VARCHAR(64) PRIMARY KEY,
    `value`         VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `settings` (`key`, `value`) VALUES ('target_amount', '4000') AS new_data
    ON DUPLICATE KEY UPDATE `value` = new_data. `value`;

INSERT INTO `members` 
  (`id`, `branch`, `name`, `amount`, `paid_months`, `paid_weeks`, `history`, `updated_at`)  
VALUES 
  (1, 'comsci41', 'นายพีรัช อิ่มผลา', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (2, 'comsci41', 'นายพรเทพ สิทธิโชติ', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (3, 'comsci41', 'นายณัฐวัฒน์ สุดพูล', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (4, 'comsci41', 'นายพลวรรธน์ บางปา', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (5, 'comsci41', 'นายสราวุธ พิมพรัตน์', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (6, 'comsci41', 'นายวรพล สมปาน', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (7, 'comsci41', 'นายไชยพัฒน์ คุ้มทรัพย์', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (8, 'comsci41', 'นายมานพ ธงสันเทียะ', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (9, 'comsci41', 'นายศรัณย์ ชินเจริญกิจ', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (10, 'comsci41', 'นายศุภัชชุติมันต์ โพธิ์ทอง', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (11, 'comsci41', 'นายกฤตศรุต ระวัง', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (12, 'comsci41', 'นายอนพัช สมบัติเปี่ยม', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (13, 'comsci41', 'นายสันติพงษ์ ธรรมาอินทร์', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (14, 'comsci41', 'นายภูริภัทร อุตมา', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (15, 'comsci41', 'นางสาวพิชชาภรณ์ อนุมาตร', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (16, 'comsci41', 'นายโพธิ์สิทธิ์ หอมสมบัติ', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (17, 'comsci41', 'นายณัฏฐชัย นิ่มแดง', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (18, 'comsci41', 'นายปภาณ สายพิน', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (19, 'comsci41', 'นายปุณณเมธ ม่วงวิเชียร', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (20, 'comsci41', 'นายอนุศิษฏ์ ชื่นเกษร', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (21, 'comsci41', 'นายกิตติธร บุพลับ', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (22, 'comsci41', 'นายณัฐดนัย วงษ์ทอง', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (23, 'comsci41', 'นายพิชญุตม์ มาลัยหอม', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (24, 'comsci41', 'นายจักรินทร์ ม่วงรอด', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (25, 'comsci41', 'นายวรฤทธิ์ อินทร์โห้', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (26, 'comsci41', 'นายณัฐวุฒิ ทองสมบัติ', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (27, 'comsci41', 'นางสาวเพชรน้ำหนึ่ง สร้อยน้ำ', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (28, 'comsci41', 'นางสาวอาทิตยา ปัญญาทร', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (29, 'comsci41', 'นายธนกร หล่อตจะกูล', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (30, 'comsci41', 'นายธีระพล อ่อนสมัย', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (31, 'comsci41', 'นายกิตติกร พึ่งรุ่ง', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (32, 'comsci41', 'นายภาณุวัฒน์ ทิพเพชร', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (33, 'comsci41', 'นายภูมิพัฒน์ นาคเฉลิม', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (34, 'comsci41', 'นายรัชชานนท์ โคยะบุตร', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (35, 'comsci41', 'นายไพโรจน์ ถิ่นวงค์ม่อม', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (36, 'comsci41', 'นางสาวณัฐริณีย์ มันทรานนท์', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (37, 'comsci41', 'นายประเสริฐ ก่อแก้ว', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (38, 'comsci41', 'นายสุกัลย์ วิริยะนุพงษ์', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (39, 'comsci41', 'นายมงคลชัย โพธิ์แสง', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21'),
  (40, 'comsci41', 'นางสาวรสิกา สายบัว', 100.00, '[false, false, false, false, false, false, false, false, false, false, false, false]', '[false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]', '[]', '2026-08-14 20:55:21');
